spring:
  application:
    name: simple-ged

  jackson:
    serialization.write_dates_as_timestamps: false
  data:
    mongodb:
      uri: 'mongodb://localhost:27017'
      database: simple-ged

logging:
  level:
    ROOT: INFO
    com.wps.poc.ged.simpleged: DEBUG

sg:
  root-location: c:\\apps\ged\sg